config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :avatars
  resources :partners
  resources :contacts

  resources :tickets

  resources :notes

  resources :activity_types

  resources :charges

  resources :content_ratings

  resources :contents

  resources :content_descriptors

  resources :content_types

  resources :activity_templates

  resources :task_templates
  resources :themes

  devise_for :users, :controllers => { :sessions => "users/sessions" }

  resources :families do
    resources :devices
      member do
      devise_for :members, class: 'Member', :controllers => { :sessions => "members/sessions" }
    end
    resources :members do
      resources :activities do
        resources :activity_details
      end
      resources :my_tasks
      resources :screen_times
      resources :st_overrides
      resources :screen_time_schedules
      member do
        post '/task_groups/:task_group_id/assign', to: "members#assign_task_group"
        post '/task_templates/assign', to: "members#assign_task_templates"
      end
    end

    resources :tasks do
      resources :task_schedules do
        resources :members do
          resources :activities do
            resources :activity_details
          end
          resources :my_tasks
          resources :screen_times
        end
      end
    end
  end

  namespace :admin do
    resources :activity_templates
    resources :activity_template_device_types
    resources :activity_types
    resources :api_devices
    resources :apps
    resources :avatars
    resources :contacts
    resources :families
    resources :task_templates
    resources :devices
    resources :device_types
    resources :task_templates
    resources :tickets
    resources :plugs
    resources :router_firmwares
    resources :router_models
    resources :routers
    resources :themes
    resources :users
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :avatars
      resources :device_types
      resources :themes
      resources :sessions
      resources :plugs
      resources :routers do
        member do
          get :devices
          post :device
        end
      end
      resources :users do
        collection do
          post :reset_password
        end
      end
      resources :task_templates
      resources :families do
        resources :activity_templates, only: [:index, :show]
        resources :tasks do
          resources :task_schedules do
            resources :schedule_rrules
          end
        end
        resources :devices do
          resources :apps_devices, path: :apps
          resources :members do
            resources :apps_members, path: :apps
          end
        end
        resources :members do
          resources :activities
          resources :apps_members, path: :apps
          resources :ledger, only: :index
          resources :my_tasks do
            member do
              post :verify
            end
          end
          resources :task_templates do
            member do
              post :assign
              delete :unassign
            end
          end
          member do
            post :buy_screen_time
          end
        end
      end
      resources :timezones
      post "/devices/:uuid/deviceDidRegister", to: 'devices#deviceDidRegister'
      patch "/devices/:udid/status", to: 'devices#status'
      post "/devices/record", to: 'devices#record'
      post "/devices/:id/apps", to: 'devices#post_apps'
      post "/devices/:id/apps/log", to: 'devices#post_applog'
      get "/devices/:id/apps", to: 'devices#get_apps'
    end
  end

  mount Stripe::Engine => "/stripe"
  get 'cities/:state', to: 'application#cities'
  get 'tos', to: 'home#tos'
  get 'privacy', to: 'home#privacy'
  get 'contact_us', to: 'home#contact_us'
  get 'support', to: 'home#support'
  get 'newsletter', to: 'home#newsletter'
  get 'privacy', to: 'home#privacy'
  get 'limit', to: 'home#limit'
  get 'protect', to: 'home#protect'
  get 'teach', to: 'home#teach'
  get 'reward', to: 'home#reward'
  get 'founders_circle', to: 'home#founders_circle'
  get 'founders_cirlce', to: 'home#founders_circle'
  get 'wizard', to: 'wizard#index'
  put 'wizard', to: 'wizard#update'
  post 'wizard', to: 'wizard#create'
  root to: 'home#index'

  match "*path", to: "errors#catch_404", via: :all

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :note_type
  has_many :note_attachments, dependent: :destroy
end

app/models/note_type.rb
class NoteType < ActiveRecord::Base
  has_many :notes
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @notes = Note.all
    respond_with(@notes)
  end

  def show
    respond_with(@note)
  end

  def new
    @note = Note.new
    respond_with(@note)
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
    @note.save
    respond_with(@note)
  end

  def update
    @note.update(note_params)
    respond_with(@note)
  end

  def destroy
    @note.destroy
    respond_with(@note)
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:ticket_id, :note_type_id, :title, :body)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :ticket_id
    = f.number_field :ticket_id
  .field
    = f.label :note_type_id
    = f.number_field :note_type_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
= link_to 'Back', notes_path

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %tr
    %th Ticket
    %th Note type
    %th Title
    %th Body
    %th
    %th
    %th

  - @notes.each do |note|
    %tr
      %td= note.ticket_id
      %td= note.note_type_id
      %td= note.title
      %td= note.body
      %td= link_to 'Show', note
      %td= link_to 'Edit', edit_note_path(note)
      %td= link_to 'Destroy', note, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Ticket:
  = @note.ticket_id
%p
  %b Note type:
  = @note.note_type_id
%p
  %b Title:
  = @note.title
%p
  %b Body:
  = @note.body

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path