config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :avatars
  resources :partners
  resources :contacts

  resources :tickets

  resources :notes

  resources :activity_types

  resources :charges

  resources :content_ratings

  resources :contents

  resources :content_descriptors

  resources :content_types

  resources :activity_templates

  resources :task_templates
  resources :themes

  devise_for :users, :controllers => { :sessions => "users/sessions" }

  resources :families do
    resources :devices
      member do
      devise_for :members, class: 'Member', :controllers => { :sessions => "members/sessions" }
    end
    resources :members do
      resources :activities do
        resources :activity_details
      end
      resources :my_tasks
      resources :screen_times
      resources :st_overrides
      resources :screen_time_schedules
      member do
        post '/task_groups/:task_group_id/assign', to: "members#assign_task_group"
        post '/task_templates/assign', to: "members#assign_task_templates"
      end
    end

    resources :tasks do
      resources :task_schedules do
        resources :members do
          resources :activities do
            resources :activity_details
          end
          resources :my_tasks
          resources :screen_times
        end
      end
    end
  end

  namespace :admin do
    resources :activity_templates
    resources :activity_template_device_types
    resources :activity_types
    resources :api_devices
    resources :apps
    resources :avatars
    resources :contacts
    resources :families
    resources :task_templates
    resources :devices
    resources :device_types
    resources :task_templates
    resources :tickets
    resources :plugs
    resources :router_firmwares
    resources :router_models
    resources :routers
    resources :themes
    resources :users
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :avatars
      resources :device_types
      resources :themes
      resources :sessions
      resources :plugs
      resources :routers do
        member do
          get :devices
          post :device
        end
      end
      resources :users do
        collection do
          post :reset_password
        end
      end
      resources :task_templates
      resources :families do
        resources :activity_templates, only: [:index, :show]
        resources :tasks do
          resources :task_schedules do
            resources :schedule_rrules
          end
        end
        resources :devices do
          resources :apps_devices, path: :apps
          resources :members do
            resources :apps_members, path: :apps
          end
        end
        resources :members do
          resources :activities
          resources :apps_members, path: :apps
          resources :ledger, only: :index
          resources :my_tasks do
            member do
              post :verify
            end
          end
          resources :task_templates do
            member do
              post :assign
              delete :unassign
            end
          end
          member do
            post :buy_screen_time
          end
        end
      end
      resources :timezones
      post "/devices/:uuid/deviceDidRegister", to: 'devices#deviceDidRegister'
      patch "/devices/:udid/status", to: 'devices#status'
      post "/devices/record", to: 'devices#record'
      post "/devices/:id/apps", to: 'devices#post_apps'
      post "/devices/:id/apps/log", to: 'devices#post_applog'
      get "/devices/:id/apps", to: 'devices#get_apps'
    end
  end

  mount Stripe::Engine => "/stripe"
  get 'cities/:state', to: 'application#cities'
  get 'tos', to: 'home#tos'
  get 'privacy', to: 'home#privacy'
  get 'contact_us', to: 'home#contact_us'
  get 'support', to: 'home#support'
  get 'newsletter', to: 'home#newsletter'
  get 'privacy', to: 'home#privacy'
  get 'limit', to: 'home#limit'
  get 'protect', to: 'home#protect'
  get 'teach', to: 'home#teach'
  get 'reward', to: 'home#reward'
  get 'founders_circle', to: 'home#founders_circle'
  get 'founders_cirlce', to: 'home#founders_circle'
  get 'wizard', to: 'wizard#index'
  put 'wizard', to: 'wizard#update'
  post 'wizard', to: 'wizard#create'
  root to: 'home#index'

  match "*path", to: "errors#catch_404", via: :all

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/content_type.rb
class ContentType < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @contents = Content.all
    respond_with(@contents)
  end

  def show
    respond_with(@content)
  end

  def new
    @content = Content.new
    respond_with(@content)
  end

  def edit
  end

  def create
    @content = Content.new(content_params)
    @content.save
    respond_with(@content)
  end

  def update
    @content.update(content_params)
    respond_with(@content)
  end

  def destroy
    @content.destroy
    respond_with(@content)
  end

  private
    def set_content
      @content = Content.find(params[:id])
    end

    def content_params
      params.require(:content).permit(:content_type_id, :title, :year, :content_rating_id, :release_date, :language_id, :description, :length, :metadata, :references)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.haml
= form_for @content do |f|
  - if @content.errors.any?
    #error_explanation
      %h2= "#{pluralize(@content.errors.count, "error")} prohibited this content from being saved:"
      %ul
        - @content.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content_type_id
    = f.number_field :content_type_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :year
    = f.text_field :year
  .field
    = f.label :content_rating_id
    = f.number_field :content_rating_id
  .field
    = f.label :release_date
    = f.date_select :release_date
  .field
    = f.label :language_id
    = f.number_field :language_id
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :length
    = f.text_field :length
  .field
    = f.label :metadata
    = f.text_area :metadata
  .field
    = f.label :references
    = f.text_area :references
  .actions
    = f.submit 'Save'

app/views/contents/edit.html.haml
%h1 Editing content

= render 'form'

= link_to 'Show', @content
\|
= link_to 'Back', contents_path

app/views/contents/index.html.haml
%h1 Listing contents

%table
  %tr
    %th Content type
    %th Title
    %th Year
    %th Content rating
    %th Release date
    %th Language
    %th Description
    %th Length
    %th Metadata
    %th References
    %th
    %th
    %th

  - @contents.each do |content|
    %tr
      %td= content.content_type_id
      %td= content.title
      %td= content.year
      %td= content.content_rating_id
      %td= content.release_date
      %td= content.language_id
      %td= content.description
      %td= content.length
      %td= content.metadata
      %td= content.references
      %td= link_to 'Show', content
      %td= link_to 'Edit', edit_content_path(content)
      %td= link_to 'Destroy', content, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Content', new_content_path

app/views/contents/new.html.haml
%h1 New content

= render 'form'

= link_to 'Back', contents_path

app/views/contents/show.html.haml
%p#notice= notice

%p
  %b Content type:
  = @content.content_type_id
%p
  %b Title:
  = @content.title
%p
  %b Year:
  = @content.year
%p
  %b Content rating:
  = @content.content_rating_id
%p
  %b Release date:
  = @content.release_date
%p
  %b Language:
  = @content.language_id
%p
  %b Description:
  = @content.description
%p
  %b Length:
  = @content.length
%p
  %b Metadata:
  = @content.metadata
%p
  %b References:
  = @content.references

= link_to 'Edit', edit_content_path(@content)
\|
= link_to 'Back', contents_path