config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :avatars
  resources :partners
  resources :contacts

  resources :tickets

  resources :notes

  resources :activity_types

  resources :charges

  resources :content_ratings

  resources :contents

  resources :content_descriptors

  resources :content_types

  resources :activity_templates

  resources :task_templates
  resources :themes

  devise_for :users, :controllers => { :sessions => "users/sessions" }

  resources :families do
    resources :devices
      member do
      devise_for :members, class: 'Member', :controllers => { :sessions => "members/sessions" }
    end
    resources :members do
      resources :activities do
        resources :activity_details
      end
      resources :my_tasks
      resources :screen_times
      resources :st_overrides
      resources :screen_time_schedules
      member do
        post '/task_groups/:task_group_id/assign', to: "members#assign_task_group"
        post '/task_templates/assign', to: "members#assign_task_templates"
      end
    end

    resources :tasks do
      resources :task_schedules do
        resources :members do
          resources :activities do
            resources :activity_details
          end
          resources :my_tasks
          resources :screen_times
        end
      end
    end
  end

  namespace :admin do
    resources :activity_templates
    resources :activity_template_device_types
    resources :activity_types
    resources :api_devices
    resources :apps
    resources :avatars
    resources :contacts
    resources :families
    resources :task_templates
    resources :devices
    resources :device_types
    resources :task_templates
    resources :tickets
    resources :plugs
    resources :router_firmwares
    resources :router_models
    resources :routers
    resources :themes
    resources :users
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :avatars
      resources :device_types
      resources :themes
      resources :sessions
      resources :plugs
      resources :routers do
        member do
          get :devices
          post :device
        end
      end
      resources :users do
        collection do
          post :reset_password
        end
      end
      resources :task_templates
      resources :families do
        resources :activity_templates, only: [:index, :show]
        resources :tasks do
          resources :task_schedules do
            resources :schedule_rrules
          end
        end
        resources :devices do
          resources :apps_devices, path: :apps
          resources :members do
            resources :apps_members, path: :apps
          end
        end
        resources :members do
          resources :activities
          resources :apps_members, path: :apps
          resources :ledger, only: :index
          resources :my_tasks do
            member do
              post :verify
            end
          end
          resources :task_templates do
            member do
              post :assign
              delete :unassign
            end
          end
          member do
            post :buy_screen_time
          end
        end
      end
      resources :timezones
      post "/devices/:uuid/deviceDidRegister", to: 'devices#deviceDidRegister'
      patch "/devices/:udid/status", to: 'devices#status'
      post "/devices/record", to: 'devices#record'
      post "/devices/:id/apps", to: 'devices#post_apps'
      post "/devices/:id/apps/log", to: 'devices#post_applog'
      get "/devices/:id/apps", to: 'devices#get_apps'
    end
  end

  mount Stripe::Engine => "/stripe"
  get 'cities/:state', to: 'application#cities'
  get 'tos', to: 'home#tos'
  get 'privacy', to: 'home#privacy'
  get 'contact_us', to: 'home#contact_us'
  get 'support', to: 'home#support'
  get 'newsletter', to: 'home#newsletter'
  get 'privacy', to: 'home#privacy'
  get 'limit', to: 'home#limit'
  get 'protect', to: 'home#protect'
  get 'teach', to: 'home#teach'
  get 'reward', to: 'home#reward'
  get 'founders_circle', to: 'home#founders_circle'
  get 'founders_cirlce', to: 'home#founders_circle'
  get 'wizard', to: 'wizard#index'
  put 'wizard', to: 'wizard#update'
  post 'wizard', to: 'wizard#create'
  root to: 'home#index'

  match "*path", to: "errors#catch_404", via: :all

end

app/models/content_rating.rb
class ContentRating < ActiveRecord::Base
end

app/controllers/content_ratings_controller.rb
class ContentRatingsController < ApplicationController
  before_action :set_content_rating, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @content_ratings = ContentRating.all
    respond_with(@content_ratings)
  end

  def show
    respond_with(@content_rating)
  end

  def new
    @content_rating = ContentRating.new
    respond_with(@content_rating)
  end

  def edit
  end

  def create
    @content_rating = ContentRating.new(content_rating_params)
    @content_rating.save
    respond_with(@content_rating)
  end

  def update
    @content_rating.update(content_rating_params)
    respond_with(@content_rating)
  end

  def destroy
    @content_rating.destroy
    respond_with(@content_rating)
  end

  private
    def set_content_rating
      @content_rating = ContentRating.find(params[:id])
    end

    def content_rating_params
      params.require(:content_rating).permit(:type, :tag, :short, :description)
    end
end

app/helpers/content_ratings_helper.rb
module ContentRatingsHelper
end

app/views/content_ratings/_form.html.haml
= form_for @content_rating do |f|
  - if @content_rating.errors.any?
    #error_explanation
      %h2= "#{pluralize(@content_rating.errors.count, "error")} prohibited this content_rating from being saved:"
      %ul
        - @content_rating.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :tag
    = f.text_field :tag
  .field
    = f.label :short
    = f.text_field :short
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/content_ratings/edit.html.haml
%h1 Editing content_rating

= render 'form'

= link_to 'Show', @content_rating
\|
= link_to 'Back', content_ratings_path

app/views/content_ratings/index.html.haml
%h1 Listing content_ratings

%table
  %tr
    %th Type
    %th Tag
    %th Short
    %th Description
    %th
    %th
    %th

  - @content_ratings.each do |content_rating|
    %tr
      %td= content_rating.type
      %td= content_rating.tag
      %td= content_rating.short
      %td= content_rating.description
      %td= link_to 'Show', content_rating
      %td= link_to 'Edit', edit_content_rating_path(content_rating)
      %td= link_to 'Destroy', content_rating, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Content rating', new_content_rating_path

app/views/content_ratings/new.html.haml
%h1 New content_rating

= render 'form'

= link_to 'Back', content_ratings_path

app/views/content_ratings/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @content_rating.type
%p
  %b Tag:
  = @content_rating.tag
%p
  %b Short:
  = @content_rating.short
%p
  %b Description:
  = @content_rating.description

= link_to 'Edit', edit_content_rating_path(@content_rating)
\|
= link_to 'Back', content_ratings_path